/** @file blackboard.c
*
* @brief Defines global elements & their accessors
*
* @par
* Copyright (c) 2021 Sunrise Labs, Inc.
* All rights reserved.
*/

#include "blackboard.h"
#include "bb_utils.h"
#include "can_msg_info.h"

#include "crc-16-x25.h"

#if defined(__cplusplus)
extern "C"
{
#endif


/**
 * @brief Initializes the Blackboard
 */
// lint has void return type no side effects
//lint -e{1762} could be made const
void bb_init(void)
{
}

/**
 * @brief Returns the BlackboardElement at the given index
 * @param idx Index to find the element at
 *
 * @return Blackboard Element at the specified index
 */
BlackboardElement_T * bb_get_element(const CANElementIndex_T idx)
{
    static Blackboard_T theBB;
    return &theBB.elements[idx];
}



////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
// *** AUTOGENERATED BY BBGEN.  DO NOT EDIT THIS SECTION: BB_C_DEF


/// @brief Auto-generated blackboard C definition for the SCM (type = BB_C_DEF) subsystem.


/**
 * @brief Gets the SCM_TestFloofy value from the blackboard.
 * Test
 * @return int32_t value of SCM_TestFloofy in Test
 */
int32_t bb_get_SCM_TestFloofy(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_SystemBarfy);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_SCM_SystemBarfy);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    const int32_t value = bb_elem_get_int32_data(bbElem, dataInfo->start_byte);
    return value;
}

/**
 * @brief Sets the SCM_TestFloofy value within the blackboard.
 * @see bb_get_SCM_TestFloofy for a description of this property.
 * @param value int32_t in Test
 */
void bb_set_SCM_TestFloofy(const int32_t value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_SystemBarfy);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_SCM_SystemBarfy);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    bb_elem_set_int32_data(bbElem, value, dataInfo->start_byte);
}

/**
 * @brief Gets the SCM_motor1Acceleration value from the blackboard.
 * Motor 1 Acceleration
 * @return int16_t value of SCM_motor1Acceleration in step/s^2
 */
float32_T bb_get_SCM_motor1Acceleration(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Params1);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Params1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    const int16_t value = bb_elem_get_int16_data(bbElem, dataInfo->start_byte);
    return bb_utils_fixed16ToFloat(value, 3U);
}

/**
 * @brief Sets the SCM_motor1Acceleration value within the blackboard.
 * @see bb_get_SCM_motor1Acceleration for a description of this property.
 * @param value int16_t in step/s^2
 */
void bb_set_SCM_motor1Acceleration(const float32_T value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Params1);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Params1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    bb_elem_set_int16_data(bbElem, bb_utils_floatToFixed16(value, 3U), dataInfo->start_byte);
}

/**
 * @brief Gets the SCM_motor1Deceleration value from the blackboard.
 * Test
 * @return int16_t value of SCM_motor1Deceleration in step/s^2
 */
float32_T bb_get_SCM_motor1Deceleration(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Params1);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Params1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[1];
    const int16_t value = bb_elem_get_int16_data(bbElem, dataInfo->start_byte);
    return bb_utils_fixed16ToFloat(value, 2U);
}

/**
 * @brief Sets the SCM_motor1Deceleration value within the blackboard.
 * @see bb_get_SCM_motor1Deceleration for a description of this property.
 * @param value int16_t in step/s^2
 */
void bb_set_SCM_motor1Deceleration(const float32_T value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Params1);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Params1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[1];
    bb_elem_set_int16_data(bbElem, bb_utils_floatToFixed16(value, 2U), dataInfo->start_byte);
}

/**
 * @brief Gets the SCM_motor1MaxSpeed value from the blackboard.
 * Test
 * @return int16_t value of SCM_motor1MaxSpeed in step/s
 */
float32_T bb_get_SCM_motor1MaxSpeed(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Params1);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Params1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[2];
    const int16_t value = bb_elem_get_int16_data(bbElem, dataInfo->start_byte);
    return bb_utils_fixed16ToFloat(value, 2U);
}

/**
 * @brief Sets the SCM_motor1MaxSpeed value within the blackboard.
 * @see bb_get_SCM_motor1MaxSpeed for a description of this property.
 * @param value int16_t in step/s
 */
void bb_set_SCM_motor1MaxSpeed(const float32_T value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Params1);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Params1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[2];
    bb_elem_set_int16_data(bbElem, bb_utils_floatToFixed16(value, 2U), dataInfo->start_byte);
}

/**
 * @brief Gets the SCM_motor1MinSpeed value from the blackboard.
 * Test
 * @return int16_t value of SCM_motor1MinSpeed in step/s
 */
float32_T bb_get_SCM_motor1MinSpeed(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Params1);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Params1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[3];
    const int16_t value = bb_elem_get_int16_data(bbElem, dataInfo->start_byte);
    return bb_utils_fixed16ToFloat(value, 2U);
}

/**
 * @brief Sets the SCM_motor1MinSpeed value within the blackboard.
 * @see bb_get_SCM_motor1MinSpeed for a description of this property.
 * @param value int16_t in step/s
 */
void bb_set_SCM_motor1MinSpeed(const float32_T value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Params1);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Params1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[3];
    bb_elem_set_int16_data(bbElem, bb_utils_floatToFixed16(value, 2U), dataInfo->start_byte);
}

/**
 * @brief Gets the SCM_Motor1Control value from the blackboard.
 * Test
 * @return int8_t value of SCM_Motor1Control in steps
 */
int8_t bb_get_SCM_Motor1Control(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Control);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Control);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    const int8_t value = bb_elem_get_int8_data(bbElem, dataInfo->start_byte);
    return value;
}

/**
 * @brief Sets the SCM_Motor1Control value within the blackboard.
 * @see bb_get_SCM_Motor1Control for a description of this property.
 * @param value int8_t in steps
 */
void bb_set_SCM_Motor1Control(const int8_t value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Control);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Control);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    bb_elem_set_int8_data(bbElem, value, dataInfo->start_byte);
}

/**
 * @brief Gets the SCM_Motor2Control value from the blackboard.
 * Test
 * @return int8_t value of SCM_Motor2Control in steps
 */
int8_t bb_get_SCM_Motor2Control(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Contro2);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Contro2);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    const int8_t value = bb_elem_get_int8_data(bbElem, dataInfo->start_byte);
    return value;
}

/**
 * @brief Sets the SCM_Motor2Control value within the blackboard.
 * @see bb_get_SCM_Motor2Control for a description of this property.
 * @param value int8_t in steps
 */
void bb_set_SCM_Motor2Control(const int8_t value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor1Contro2);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_SCM_Motor1Contro2);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    bb_elem_set_int8_data(bbElem, value, dataInfo->start_byte);
}

/**
 * @brief Gets the SCM_Motor3Control value from the blackboard.
 * Test
 * @return int8_t value of SCM_Motor3Control in steps
 */
int8_t bb_get_SCM_Motor3Control(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor3Control);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_SCM_Motor3Control);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    const int8_t value = bb_elem_get_int8_data(bbElem, dataInfo->start_byte);
    return value;
}

/**
 * @brief Sets the SCM_Motor3Control value within the blackboard.
 * @see bb_get_SCM_Motor3Control for a description of this property.
 * @param value int8_t in steps
 */
void bb_set_SCM_Motor3Control(const int8_t value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_SCM_Motor3Control);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_SCM_Motor3Control);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    bb_elem_set_int8_data(bbElem, value, dataInfo->start_byte);
}

/**
 * @brief Gets the RCM_ModuleId value from the blackboard.
 * RCM Module ID
 * @return int8_t value of RCM_ModuleId in data
 */
int8_t bb_get_RCM_ModuleId(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_System);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_RCM_System);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    const int8_t value = bb_elem_get_int8_data(bbElem, dataInfo->start_byte);
    return value;
}

/**
 * @brief Sets the RCM_ModuleId value within the blackboard.
 * @see bb_get_RCM_ModuleId for a description of this property.
 * @param value int8_t in data
 */
void bb_set_RCM_ModuleId(const int8_t value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_System);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_RCM_System);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    bb_elem_set_int8_data(bbElem, value, dataInfo->start_byte);
}

/**
 * @brief Gets the RCM_Sensor1Voltage value from the blackboard.
 * Voltage for Sensor 1
 * @return int16_t value of RCM_Sensor1Voltage in V
 */
float32_T bb_get_RCM_Sensor1Voltage(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_Sensor1);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_RCM_Sensor1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    const int16_t value = bb_elem_get_int16_data(bbElem, dataInfo->start_byte);
    return bb_utils_fixed16ToFloat(value, 3U);
}

/**
 * @brief Sets the RCM_Sensor1Voltage value within the blackboard.
 * @see bb_get_RCM_Sensor1Voltage for a description of this property.
 * @param value int16_t in V
 */
void bb_set_RCM_Sensor1Voltage(const float32_T value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_Sensor1);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_RCM_Sensor1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[0];
    bb_elem_set_int16_data(bbElem, bb_utils_floatToFixed16(value, 3U), dataInfo->start_byte);
}

/**
 * @brief Gets the RCM_Sensor1Temperature value from the blackboard.
 * Temperature for Sensor 1
 * @return int16_t value of RCM_Sensor1Temperature in C
 */
float32_T bb_get_RCM_Sensor1Temperature(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_Sensor1);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_RCM_Sensor1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[1];
    const int16_t value = bb_elem_get_int16_data(bbElem, dataInfo->start_byte);
    return bb_utils_fixed16ToFloat(value, 3U);
}

/**
 * @brief Sets the RCM_Sensor1Temperature value within the blackboard.
 * @see bb_get_RCM_Sensor1Temperature for a description of this property.
 * @param value int16_t in C
 */
void bb_set_RCM_Sensor1Temperature(const float32_T value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_Sensor1);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_RCM_Sensor1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[1];
    bb_elem_set_int16_data(bbElem, bb_utils_floatToFixed16(value, 3U), dataInfo->start_byte);
}

/**
 * @brief Gets the RCM_Sensor1Foo value from the blackboard.
 * Voltage for Sensor 1
 * @return int16_t value of RCM_Sensor1Foo in V
 */
float32_T bb_get_RCM_Sensor1Foo(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_Sensor1);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_RCM_Sensor1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[2];
    const int16_t value = bb_elem_get_int16_data(bbElem, dataInfo->start_byte);
    return bb_utils_fixed16ToFloat(value, 3U);
}

/**
 * @brief Sets the RCM_Sensor1Foo value within the blackboard.
 * @see bb_get_RCM_Sensor1Foo for a description of this property.
 * @param value int16_t in V
 */
void bb_set_RCM_Sensor1Foo(const float32_T value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_Sensor1);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_RCM_Sensor1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[2];
    bb_elem_set_int16_data(bbElem, bb_utils_floatToFixed16(value, 3U), dataInfo->start_byte);
}

/**
 * @brief Gets the RCM_Sensor1Bar value from the blackboard.
 * Temperature for Sensor 1
 * @return int16_t value of RCM_Sensor1Bar in C
 */
float32_T bb_get_RCM_Sensor1Bar(void)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_Sensor1);
    const BlackboardElement_T * const bbElem = bb_get_element(CAN_ELEM_RCM_Sensor1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[3];
    const int16_t value = bb_elem_get_int16_data(bbElem, dataInfo->start_byte);
    return bb_utils_fixed16ToFloat(value, 3U);
}

/**
 * @brief Sets the RCM_Sensor1Bar value within the blackboard.
 * @see bb_get_RCM_Sensor1Bar for a description of this property.
 * @param value int16_t in C
 */
void bb_set_RCM_Sensor1Bar(const float32_T value)
{
    const CANMsgInfo_T * canMsgInfo = can_elem_get_can_msg_info_idx(CAN_ELEM_RCM_Sensor1);
    BlackboardElement_T * bbElem = bb_get_element(CAN_ELEM_RCM_Sensor1);
    const CANDataInfo_T * dataInfo = &canMsgInfo->data_info[3];
    bb_elem_set_int16_data(bbElem, bb_utils_floatToFixed16(value, 3U), dataInfo->start_byte);
}


// *** AUTOGENERATED BY BBGEN.  DO NOT EDIT THIS SECTION: BB_C_DEF
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////


#if defined(__cplusplus)
}
#endif

