#include "can_elem.h"

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
// *** AUTOGENERATED BY BBGEN.  DO NOT EDIT THIS SECTION: CAN_SPEC_SCHED_C_DEF

/// @brief Auto-generated CAN spec definition for scheduling for the SCM (type = CAN_SPEC_SCHED_C_DEF) subsystem.

static constexpr CANElement_T can_spec_can_element_sched_list[CAN_ELEM_LAST_MSG] =
{
    {
        /* .canMsgInfo */
        {
            0x400                                    /* id        */,
            "SCM_SystemBarfy"                        /* name      */,
            100                                      /* period_ms */,
            4                                        /* numBytes  */,
            {   /* data_info */
                /* name                              signed_val         start_byte byte_count */
                { "TestFloofy",                      CAN_DATA_SIGNED,   0,         4 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },

            }
        },
        {
            /* Callbacks always null for scheduling calculations */
            NULL,
            NULL
        },
        (CanChannel_T)((uint16_t)(CAN_CHAN1) | (uint16_t)(CAN_CHAN2))  /* txChan */,
        CAN_CHAN1  /* rxChan */
    },
    {
        /* .canMsgInfo */
        {
            0x410                                    /* id        */,
            "SCM_Motor1Params1"                      /* name      */,
            100                                      /* period_ms */,
            8                                        /* numBytes  */,
            {   /* data_info */
                /* name                              signed_val         start_byte byte_count */
                { "motor1Acceleration",              CAN_DATA_SIGNED,   0,         2 },
                { "motor1Deceleration",              CAN_DATA_SIGNED,   2,         2 },
                { "motor1MaxSpeed",                  CAN_DATA_SIGNED,   4,         2 },
                { "motor1MinSpeed",                  CAN_DATA_SIGNED,   6,         2 },

            }
        },
        {
            /* Callbacks always null for scheduling calculations */
            NULL,
            NULL
        },
        CAN_CHAN1  /* txChan */,
        CAN_NONE  /* rxChan */
    },
    {
        /* .canMsgInfo */
        {
            0x460                                    /* id        */,
            "SCM_Motor1Control"                      /* name      */,
            100                                      /* period_ms */,
            1                                        /* numBytes  */,
            {   /* data_info */
                /* name                              signed_val         start_byte byte_count */
                { "Motor1Control",                   CAN_DATA_SIGNED,   0,         1 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },

            }
        },
        {
            /* Callbacks always null for scheduling calculations */
            NULL,
            NULL
        },
        CAN_CHAN1  /* txChan */,
        CAN_NONE  /* rxChan */
    },
    {
        /* .canMsgInfo */
        {
            0x630                                    /* id        */,
            "RCM_System"                             /* name      */,
            100                                      /* period_ms */,
            1                                        /* numBytes  */,
            {   /* data_info */
                /* name                              signed_val         start_byte byte_count */
                { "ModuleId",                        CAN_DATA_SIGNED,   0,         1 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },
                { NULL_STR,                          CAN_DATA_UNSIGNED, 0,         0 },

            }
        },
        {
            /* Callbacks always null for scheduling calculations */
            NULL,
            NULL
        },
        CAN_NONE  /* txChan */,
        CAN_CHAN1  /* rxChan */
    },
    {
        /* .canMsgInfo */
        {
            0x631                                    /* id        */,
            "RCM_Sensor1"                            /* name      */,
            100                                      /* period_ms */,
            8                                        /* numBytes  */,
            {   /* data_info */
                /* name                              signed_val         start_byte byte_count */
                { "Sensor1Voltage",                  CAN_DATA_SIGNED,   0,         2 },
                { "Sensor1Temperature",              CAN_DATA_SIGNED,   2,         2 },
                { "Sensor1Foo",                      CAN_DATA_SIGNED,   4,         2 },
                { "Sensor1Bar",                      CAN_DATA_SIGNED,   6,         2 },

            }
        },
        {
            /* Callbacks always null for scheduling calculations */
            NULL,
            NULL
        },
        CAN_NONE  /* txChan */,
        CAN_CHAN1  /* rxChan */
    },

};

    // *** AUTOGENERATED BY BBGEN.  DO NOT EDIT THIS SECTION: CAN_SPEC_SCHED_C_DEF
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
