/** @file canspec.h
*
* @brief Declares a list of can elements for the SCM and an associated enum of
* indexes for the elements
*
* @par
* Copyright (c) 2021 Sunrise Labs, Inc.
* All rights reserved.
*/

#ifndef CAN_SPEC_H
#define CAN_SPEC_H

#include "scm_can_spec.h"

#define TIME_TICK_FREQUENCY_HZ (uint32_t)(200)
#define BB_PORT_MS_TO_TICKS(ms) (TIME_TICK_FREQUENCY_HZ * (ms) / (uint32_t)1000)

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
// *** AUTOGENERATED BY BBGEN.  DO NOT EDIT THIS SECTION: CAN_SPEC_C_DECL


/// @brief Auto-generated CAN specialization declaration for the SCM (type = CAN_SPEC_C_DECL) subsystem.

typedef enum
{
    CAN_ELEM_SCM_SystemBarfy,
    CAN_ELEM_SCM_Motor1Params1,
    CAN_ELEM_SCM_Motor1Control,
    CAN_ELEM_RCM_System,
    CAN_ELEM_RCM_Sensor1,

    // Last item can be used as a count
    CAN_ELEM_LAST_MSG
} CANElementIndex_T;

// can_elem.h and can_spec.h have a carefully crafted inter-dependency since they are really one
// file auto-generated in one half and fixed code in the other. Take care about changing the
// order/location of includes.
#include "can_elem.h"
extern const CANElement_T can_spec_can_element_list[CAN_ELEM_LAST_MSG];

// *** AUTOGENERATED BY BBGEN.  DO NOT EDIT THIS SECTION: CAN_SPEC_C_DECL
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

#endif // CAN_SPEC_H
